"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TodoistColorNames = exports.TODOIST_COLOR_SETTING = exports.TODOIST_COLOR_NAMES = exports.TAG_COLOR_NAMES = exports.SYNC_DIRECTION = exports.SYNC_DIRECTION_VALUES = exports.SYNC_STATUS = void 0;
exports.SYNC_STATUS = {
    ACTIVE: 'active',
    ERROR: 'error',
    SUCCESS: 'success',
};
exports.SYNC_DIRECTION_VALUES = ['both', 'import', 'export'];
exports.SYNC_DIRECTION = {
    BOTH: 'both',
    IMPORT: 'import',
    EXPORT: 'export',
};
exports.TAG_COLOR_NAMES = [
    'default',
    'red',
    'orange',
    'yellow',
    'olive',
    'green',
    'teal',
    'blue',
    'violet',
    'purple',
    'pink',
    'brown',
    'grey',
    'black',
];
exports.TODOIST_COLOR_NAMES = [
    'berry red',
    'red',
    'orange',
    'yellow',
    'olive green',
    'lime green',
    'green',
    'mint green',
    'teal',
    'sky blue',
    'light blue',
    'blue',
    'grape',
    'violet',
    'lavender',
    'magenta',
    'salmon',
    'charcoal',
    'grey',
    'taupe',
];
exports.TODOIST_COLOR_SETTING = {
    BERRY_RED: 'berry red',
    RED: 'red',
    ORANGE: 'orange',
    YELLOW: 'yellow',
    OLIVE_GREEN: 'olive green',
    LIME_GREEN: 'lime green',
    GREEN: 'green',
    MINT_GREEN: 'mint green',
    TEAL: 'teal',
    SKY_BLUE: 'sky blue',
    LIGHT_BLUE: 'light blue',
    BLUE: 'blue',
    GRAPE: 'grape',
    VIOLET: 'violet',
    LAVENDER: 'lavender',
    MAGENTA: 'magenta',
    SALMON: 'salmon',
    CHARCOAL: 'charcoal',
    GREY: 'grey',
    TAUPE: 'taupe',
};
exports.TodoistColorNames = {
    'berry red': 30 /* TodoistColor.BERRY_RED */,
    red: 31 /* TodoistColor.RED */,
    orange: 32 /* TodoistColor.ORANGE */,
    yellow: 33 /* TodoistColor.YELLOW */,
    'olive green': 34 /* TodoistColor.OLIVE_GREEN */,
    'lime green': 35 /* TodoistColor.LIME_GREEN */,
    green: 36 /* TodoistColor.GREEN */,
    'mint green': 37 /* TodoistColor.MINT_GREEN */,
    teal: 38 /* TodoistColor.TEAL */,
    'sky blue': 39 /* TodoistColor.SKY_BLUE */,
    'light blue': 40 /* TodoistColor.LIGHT_BLUE */,
    blue: 41 /* TodoistColor.BLUE */,
    grape: 42 /* TodoistColor.GRAPE */,
    violet: 43 /* TodoistColor.VIOLET */,
    lavender: 44 /* TodoistColor.LAVENDER */,
    magenta: 45 /* TodoistColor.MAGENTA */,
    salmon: 46 /* TodoistColor.SALMON */,
    charcoal: 47 /* TodoistColor.CHARCOAL */,
    grey: 48 /* TodoistColor.GREY */,
    taupe: 49 /* TodoistColor.TAUPE */,
};
//# sourceMappingURL=types.js.map